### ISSUE TITLE
スマートフォンで表示するとvideo領域が小さい

### ISSUE THREAD

**Issue by rksan** [rksan/barcode-detection-api-demo#1]
PCでは1280*720で表示できるが、スマートフォンでは表示できない。

**Comment by rksan** [comment]
![Screenshot_20230306-180729.png](https://user-images.githubusercontent.com/48819681/223065553-bdbd52a8-e400-441e-8daa-2df18fa66e49.png)

**Comment by rksan** [comment]
height< width の場合は、ratio =19/6、width < height の場合は、ratio = 9/16 にする事で対応

```css
.viewport {
  position: relative;
  display: inline-block;
  max-width: 100%;
  max-height: 100%;
  width: auto;
  height: 100%;
  aspect-ratio: 16/9;
}

/* height > width */
@media (orientation: portrait) {
  .viewport {
    width: 100%;
    height: auto;
    aspect-ratio: 9/16;
  }
}
```
